# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: 👾 Android

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  STABLE_GODOT_VERSION: 3.2.3

jobs:
  android-template:
    name: Running on Godot Scons
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Download and prepare the Stable Godot .AAR LIB
      run: | 
        cd android/admob/godot-lib 
        #variables
        GODOT_AAR_LIB="godot-lib.aar"
        GODOT_AAR_FILENAME="godot-lib.${{env.STABLE_GODOT_VERSION}}.stable.release.aar"
        FULL_PATHNAME_DOWNLOAD_GODOT_AAR="https://downloads.tuxfamily.org/godotengine/${{env.STABLE_GODOT_VERSION}}/${GODOT_AAR_FILENAME}"
        #get file on Godot's server and rename
        wget $FULL_PATHNAME_DOWNLOAD_GODOT_AAR
        mv $GODOT_AAR_FILENAME $GODOT_AAR_LIB
    
    - name: Grant execute permission for gradlew
      run: |
        cd android/admob
        chmod +x gradlew
        
    - name: Build with Gradle
      run: | 
        cd android/admob
        ./gradlew clean 
        ./gradlew build
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ github.job }}
        path: godot-${{env.STABLE_GODOT_VERSION}}-stable/bin/*