name: Copy admob_api/
on:
  push:
    paths: 
      - 'example/admob_api/**'
    branches: [ master ]
  pull_request:
    paths: 
      - 'example/admob_api/**'
    branches: [ master ]

jobs:
  copy:
    name: Copying example/admob_api/
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Copy the admob_api/
      run: |
        rm -r admob_api/
        cp -Rf example/admob_api admob_api/
    
    - name: Declare SHA
      id: vars
      shell: bash
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add admob_api/
        git status
        git commit -m "Copied from "example/admob_api", SHA: ${{ steps.vars.outputs.sha_short }}"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
