name: Export for Android and iOS
on:
  workflow_run:
    workflows: [ "Build iOS", "Build Android" ]
    types: 
      - completed
  push:
    paths: 
      - '.github/workflows/export_android_ios_project.yml'
    branches: [ master ]
jobs:
  export:
    name: Export and Upload Artifact
    runs-on: ubuntu-latest
    strategy:
      matrix:
        GODOT_VERSIONS: [3.2.3]
    steps:
    - uses: actions/checkout@v2

    - name: Downloading templates 
      run: |
        wget -nv https://downloads.tuxfamily.org/godotengine/${{matrix.GODOT_VERSIONS}}/Godot_v${{matrix.GODOT_VERSIONS}}-stable_export_templates.tpz 

    - name: Install Android Build Template
      run: |
        unzip Godot_v${{matrix.GODOT_VERSIONS}}-stable_export_templates.tpz
        wget -nv https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/releases/download/Android_v3.2.2%2B/android-template-v${{matrix.GODOT_VERSIONS}}.zip
        mkdir example/android
        mkdir example/android/plugins
        mkdir example/android/build
        echo "${{matrix.GODOT_VERSIONS}}.stable" >> example/android/.build_version
        unzip android-template-v${{matrix.GODOT_VERSIONS}}.zip -d example/android/plugins
        unzip templates/android_source.zip -d example/android/build

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2.0.1

    - name: Install Android Platform
      run: |
        sdkmanager "platform-tools"
        sdkmanager "platforms;android-29"
        sdkmanager "build-tools;29.0.2"
        
    - name: Verify Android bin ADB
      run: cd /usr/local/lib && ls

    - name: Change AndroidManifest.xml
      run: |
        sudo apt-get update -y
        sudo apt-get install -y xmlstarlet
        cd example/android/build
        xmlstarlet ed --subnode "/manifest/application" --type elem -n meta-data -v "" AndroidManifest.xml | \
        xmlstarlet ed --insert "/manifest/application/meta-data[last()]" --type attr -n android:name -v com.google.android.gms.ads.APPLICATION_ID | \
        xmlstarlet ed --insert "/manifest/application/meta-data[last()]" --type attr -n android:value -v ca-app-pub-3940256099942544~3347511713 > output.xml
        mv output.xml AndroidManifest.xml
        cat AndroidManifest.xml
        ls

    - name: Export AdMob example to iOS
      # Use latest version (see releases for all versions)
      uses: firebelley/godot-export@v2.6.0
      with:
        # Defining all the required inputs
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/${{matrix.GODOT_VERSIONS}}/Godot_v${{matrix.GODOT_VERSIONS}}-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/${{matrix.GODOT_VERSIONS}}/Godot_v${{matrix.GODOT_VERSIONS}}-stable_export_templates.tpz
        relative_project_path: ./example/
        use_preset_export_path: true
        create_release: false
        export_debug: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    - name: Download ios-template from iOS Tag and rename .a file by ios-template downloaded
      run: |
        cd ../builds/ios/iOS
        wget "https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/releases/download/iOS_v3.0%2B/ios-template-v${{matrix.GODOT_VERSIONS}}.zip"
        unzip ios-template-v${{matrix.GODOT_VERSIONS}}.zip
        rm ios-template-v${{matrix.GODOT_VERSIONS}}.zip
        rm AdMob.a
        mv libgodot.iphone.release.fat.a AdMob.a 
        ls


    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: AdMobiOS
        path: /home/runner/work/Godot-AdMob-Android-iOS/builds/ios/iOS/

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: AdMobAndroid
        path: /home/runner/work/Godot-AdMob-Android-iOS/builds/android/Android/

  test:
    needs: [export]
    name: Test on Xcode
    runs-on: macos-latest
    
    steps:

    - name: Download artifacts
      uses: actions/download-artifact@v2
        
    - name: Unzip project
      run: |
        cd AdMob
        unzip googlemobileadssdkios.zip
        rm googlemobileadssdkios.zip

    - uses: sersoft-gmbh/xcodebuild-action@v1
      with:
        project: AdMob/AdMob.xcodeproj
        configuration: Debug
        action: build
        sdk: iphonesimulator14.0
        build-settings: -target AdMob -arch x86_64 -allowProvisioningUpdates OTHER_LDFLAGS="-ObjC" FRAMEWORK_SEARCH_PATHS="/Users/runner/work/Godot-AdMob-Android-iOS/Godot-AdMob-Android-iOS/AdMob/GoogleMobileAdsSdkiOS-7.68.0/GoogleMobileAds.xcframework/ios-i386_x86_64-simulator"
            OTHER_LIBTOOLFLAGS="/Users/runner/work/Godot-AdMob-Android-iOS/Godot-AdMob-Android-iOS/AdMob/GoogleMobileAdsSdkiOS-7.68.0/GoogleMobileAds.xcframework/ios-i386_x86_64-simulator"

