name: (NOT WORKING) Export and Test on XCode
on:
  #workflow_run:
  #  workflows: [ "Build iOS" ]
  #  types: 
  #    - completed
  push:
    paths: 
      - '.github/workflows/export_ios_project.yml'
    branches: [ master ]
jobs:
  export:
    name: Export and Upload Artifact
    runs-on: ubuntu-latest
    strategy:
      matrix:
        GODOT_VERSIONS: [3.2.3]
    steps:
    - uses: actions/checkout@v2
      
    - name: Export AdMob example to iOS
      # Use latest version (see releases for all versions)
      uses: firebelley/godot-export@v2.6.0
      with:
        # Defining all the required inputs
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/${{matrix.GODOT_VERSIONS}}/Godot_v${{matrix.GODOT_VERSIONS}}-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/${{matrix.GODOT_VERSIONS}}/Godot_v${{matrix.GODOT_VERSIONS}}-stable_export_templates.tpz
        relative_project_path: ./example/
        use_preset_export_path: true
        create_release: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Download ios-template from iOS Tag and rename .a file by ios-template downloaded
      run: |
        cd ../builds/ios/iOS
        wget "https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/releases/download/iOS_v3.0%2B/ios-template-v${{matrix.GODOT_VERSIONS}}.zip"
        unzip ios-template-v${{matrix.GODOT_VERSIONS}}.zip
        rm ios-template-v${{matrix.GODOT_VERSIONS}}.zip
        rm AdMob.a
        mv libgodot.iphone.release.fat.a AdMob.a 
        ls

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: AdMob
        path: /home/runner/work/Godot-AdMob-Android-iOS/builds/ios/iOS/

  test:
    needs: [export]
    name: Test on Xcode
    runs-on: macos-latest
    
    steps:

    - name: Download artifacts
      uses: actions/download-artifact@v2
        
    - name: Unzip project
      run: |
        cd AdMob
        ls

    - name: Test on XCode
      run: |
        cd AdMob
        unzip googlemobileadssdkios.zip
        rm googlemobileadssdkios.zip
        pwd
        xcodebuild -help
        
        xcodebuild -target AdMob \
        -configuration Debug build \
        -allowProvisioningUpdates \
        -sdk iphonesimulator14.0 \
        OTHER_LDFLAGS="-ObjC" \
        FRAMEWORK_SEARCH_PATHS = "/Users/runner/work/Godot-AdMob-Android-iOS/Godot-AdMob-Android-iOS/AdMob/GoogleMobileAdsSdkiOS-7.68.0/GoogleMobileAds.xcframework/ios-i386_x86_64-simulator" \
        OTHER_LIBTOOLFLAGS="/Users/runner/work/Godot-AdMob-Android-iOS/Godot-AdMob-Android-iOS/AdMob/GoogleMobileAdsSdkiOS-7.68.0/GoogleMobileAds.xcframework/ios-i386_x86_64-simulator" \
        -arch x86_64
