name: 🍎 iOS with Scons

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  STABLE_GODOT_VERSION: 3.2.3
  STABLE_GODOT_VERSION_FULLNAME: godot-${{env.STABLE_GODOT_VERSION}}-stable

jobs:
  build:
    runs-on: "macos-latest"

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.x'
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: 'x64'
    - name: Configuring Python packages
      run: |
        python -c "import sys; print(sys.version)"
        python -m pip install scons
        python --version
        scons --version
    - name: Download and unzip stable Godot version source code
      run: |
        FULL_PATHNAME_DOWNLOAD_GODOT_SOURCE_CODE="https://github.com/godotengine/godot/archive/${{env.STABLE_GODOT_VERSION}}-stable.zip"
        curl -LO $FULL_PATHNAME_DOWNLOAD_GODOT_SOURCE_CODE
        mv ${{env.STABLE_GODOT_VERSION}}-stable.zip ${{env.STABLE_GODOT_VERSION_FULLNAME}}
        unzip ${{env.STABLE_GODOT_VERSION}}-stable.zip
        ls
    - name: Download and unzip the lastest Google Mobile Ads SDK on iOS module folder
      run: |
        curl -LO https://dl.google.com/googleadmobadssdk/googlemobileadssdkios.zip
        ls
        unzip googlemobileadssdkios.zip
        mv googlemobileadssdkios/ ios/admob/lib/

    - name: Move the iOS module to Godot's /modules folder
      run: |
        ls
        mv ios/admob godot-${{env.STABLE_GODOT_VERSION}}-stable/modules/
    - name: Compiles the Source Code
      run: |
        cd ${{env.STABLE_GODOT_VERSION_FULLNAME}}
        ls
        scons p=iphone target=release
