name: 🍎 iOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  STABLE_GODOT_VERSION: 3.2.3

jobs:
  ios-template:
    name: Running on Gradle
    runs-on: "macos-latest"

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.x'
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: 'x64'
    - name: Configuring Python packages
      run: |
        python -c "import sys; print(sys.version)"
        python -m pip install scons
        python --version
        scons --version
    - name: Download and unzip stable Godot version source code
      run: |
        FULL_PATHNAME_DOWNLOAD_GODOT_SOURCE_CODE="https://github.com/godotengine/godot/archive/${{env.STABLE_GODOT_VERSION}}-stable.zip"
        curl -LO $FULL_PATHNAME_DOWNLOAD_GODOT_SOURCE_CODE
        unzip ${{env.STABLE_GODOT_VERSION}}-stable.zip
        ls
    - name: Download and unzip the lastest Google Mobile Ads SDK on iOS module folder
      run: |
        curl -LO https://dl.google.com/googleadmobadssdk/googlemobileadssdkios.zip
        unzip googlemobileadssdkios.zip -d ios/admob/lib/
        cd ios/admob/lib
        cd */
        mv * ../
        
    - name: Move the iOS module to Godot's /modules folder
      run: |
        ls
        mv ios/admob godot-${{env.STABLE_GODOT_VERSION}}-stable/modules/
        cd godot-${{env.STABLE_GODOT_VERSION}}-stable/modules/
        ls
        cd admob
        ls
    - name: Compiles the Source Code
      run: |
        cd godot-${{env.STABLE_GODOT_VERSION}}-stable
        ls
        scons p=iphone tools=no target=release arch=arm64
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ github.job }}
        path: godot-${{env.STABLE_GODOT_VERSION}}-stable/bin/*