name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  STABLE_GODOT_VERSION: 3.2.3
  RELEASE_NAME : Release build Android + iOS 

jobs:
  android-ios-template:
    name: Compiling with Scons (iOS) and Gradle (Android)
    runs-on: "macos-latest"

    steps:
    - uses: actions/checkout@v2
    - name: Generate Changelog
      run: echo "# Good things have arrived" > ${{ github.workflow }}-CHANGELOG.txt

    - name: Bump version and push tag
      uses: mathieudutour/github-tag-action@v4.6
      with:
        custom_tag : ${{env.STABLE_GODOT_VERSION}}
        github_token: ${{ secrets.GITHUB_TOKEN }}

    # Upload cache on completion and check it out now
    - name: Load .scons_cache directory
      id: ios-template-cache
      uses: actions/cache@v2
      with:
        path: ${{github.workspace}}/godot-${{env.STABLE_GODOT_VERSION}}-stable/.scons_cache/
        key: ${{github.job}}-master-${{github.ref}}-${{github.sha}}
        restore-keys: |
          ${{github.job}}-master-${{github.ref}}-${{github.sha}}
          ${{github.job}}-master-${{github.ref}}
          ${{github.job}}-master

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.x'
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: 'x64'

    - name: Configuring Python packages
      run: |
        python -c "import sys; print(sys.version)"
        python -m pip install scons
        python --version
        scons --version

    - name: Download and unzip stable Godot version source code
      run: |
        FULL_PATHNAME_DOWNLOAD_GODOT_SOURCE_CODE="https://github.com/godotengine/godot/archive/${{env.STABLE_GODOT_VERSION}}-stable.zip"
        curl -LO $FULL_PATHNAME_DOWNLOAD_GODOT_SOURCE_CODE
        unzip ${{env.STABLE_GODOT_VERSION}}-stable.zip

    - name: Download and unzip the lastest Google Mobile Ads SDK on iOS module folder
      run: |
        curl -LO https://dl.google.com/googleadmobadssdk/googlemobileadssdkios.zip
        unzip googlemobileadssdkios.zip -d ios/admob/lib/
        cd ios/admob/lib
        cd */
        mv * ../

    - name: Move the iOS module to Godot's /modules folder
      run: |
        mv ios/admob godot-${{env.STABLE_GODOT_VERSION}}-stable/modules/
        cd godot-${{env.STABLE_GODOT_VERSION}}-stable/modules/

    - name: Compiles the Source Code
      env:
        SCONS_CACHE: ${{github.workspace}}/godot-${{env.STABLE_GODOT_VERSION}}-stable/.scons_cache/
      run: |
        cd godot-${{env.STABLE_GODOT_VERSION}}-stable
        mkdir -p bin/release/
        scons p=iphone tools=no target=release arch=arm
        scons p=iphone tools=no target=release arch=arm64
        echo "LIPO COMMANDS"
        lipo -create bin/libgodot.iphone.opt.arm.a bin/libgodot.iphone.opt.arm64.a -output bin/release/libgodot.iphone.release.fat.a
        lipo -create bin/libgodot_camera_module.iphone.opt.arm.a bin/libgodot_camera_module.iphone.opt.arm64.a -output bin/release/libgodot_camera_module.iphone.release.fat.a
        lipo -create bin/libgodot_arkit_module.iphone.opt.arm.a bin/libgodot_arkit_module.iphone.opt.arm64.a -output bin/release/libgodot_arkit_module.iphone.release.fat.a
        
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Download and prepare the Stable Godot .AAR LIB
      run: | 
        cd android/admob/godot-lib 
        #variables
        GODOT_AAR_LIB="godot-lib.aar"
        GODOT_AAR_FILENAME="godot-lib.${{env.STABLE_GODOT_VERSION}}.stable.release.aar"
        FULL_PATHNAME_DOWNLOAD_GODOT_AAR="https://downloads.tuxfamily.org/godotengine/${{env.STABLE_GODOT_VERSION}}/${GODOT_AAR_FILENAME}"
        #get file on Godot's server and rename
        wget $FULL_PATHNAME_DOWNLOAD_GODOT_AAR
        mv $GODOT_AAR_FILENAME $GODOT_AAR_LIB
    
    - name: Grant execute permission for gradlew
      run: |
        cd android/admob
        chmod +x gradlew
        
    - name: Build with Gradle
      run: | 
        cd android/admob
        ./gradlew build

    - name: Compress the binaries
      run: |
        zip -j android-template.zip android/admob/admob/build/outputs/aar/*
        zip -j ios-template.zip godot-${{env.STABLE_GODOT_VERSION}}-stable/bin/release/*

